### ISSUE TITLE
下载数据集遇到的问题

### ISSUE THREAD

**Issue by bohuisir** [csjliang/LPTN#31]
当我执行PYTHONPATH="./:${PYTHONPATH}" python scripts/data_preparation/download_datasets.py时
报了以下错误，是链接失效了吗
Traceback (most recent call last):
  File "scripts/data_preparation/download_datasets.py", line 56, in <module>
    download_dataset(file_ids[dataset])
  File "scripts/data_preparation/download_datasets.py", line 26, in download_dataset
    download_file_from_google_drive(file_id, save_path)
  File "/mnt/lbh/new/Problems/LPTN-main/codes/utils/download_util.py", line 23, in download_file_from_google_drive
    response = session.get(URL, params=params, stream=True)
  File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1oAORKd-TPnPwZvhcnEEJqc1ogT7KgFtx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0325ff1310>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by hangxiaotian** [comment]
I run into the same question.

**Comment by hangxiaotian** [comment]
> 当我执行PYTHONPATH="./:${PYTHONPATH}" python scripts/data_preparation/download_datasets.py时 报了以下错误，是链接失效了吗 Traceback (most recent call last): File "scripts/data_preparation/download_datasets.py", line 56, in download_dataset(file_ids[dataset]) File "scripts/data_preparation/download_datasets.py", line 26, in download_dataset download_file_from_google_drive(file_id, save_path) File "/mnt/lbh/new/Problems/LPTN-main/codes/utils/download_util.py", line 23, in download_file_from_google_drive response = session.get(URL, params=params, stream=True) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 546, in get return self.request('GET', url, **kwargs) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request resp = self.send(prep, **send_kwargs) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1oAORKd-TPnPwZvhcnEEJqc1ogT7KgFtx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0325ff1310>: Failed to establish a new connection: [Errno 110] Connection timed out'))

你解决了吗

**Comment by bohuisir** [comment]
> > 当我执行PYTHONPATH="./:${PYTHONPATH}" python scripts/data_preparation/download_datasets.py时 报了以下错误，是链接失效了吗 Traceback (most recent call last): File "scripts/data_preparation/download_datasets.py", line 56, in download_dataset(file_ids[dataset]) File "scripts/data_preparation/download_datasets.py", line 26, in download_dataset download_file_from_google_drive(file_id, save_path) File "/mnt/lbh/new/Problems/LPTN-main/codes/utils/download_util.py", line 23, in download_file_from_google_drive response = session.get(URL, params=params, stream=True) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 546, in get return self.request('GET', url, **kwargs) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request resp = self.send(prep, **send_kwargs) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1oAORKd-TPnPwZvhcnEEJqc1ogT7KgFtx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0325ff1310>: Failed to establish a new connection: [Errno 110] Connection timed out'))
> 
> 你解决了吗

我没有找到相应的数据集，你找到了吗

**Comment by hangxiaotian** [comment]
我也没有呢，数据集下载报错，作者不回复邮件！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 晚上7:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [csjliang/LPTN] 下载数据集遇到的问题 (#31)





   
当我执行PYTHONPATH="./:${PYTHONPATH}" python scripts/data_preparation/download_datasets.py时 报了以下错误，是链接失效了吗 Traceback (most recent call last): File "scripts/data_preparation/download_datasets.py", line 56, in download_dataset(file_ids[dataset]) File "scripts/data_preparation/download_datasets.py", line 26, in download_dataset download_file_from_google_drive(file_id, save_path) File "/mnt/lbh/new/Problems/LPTN-main/codes/utils/download_util.py", line 23, in download_file_from_google_drive response = session.get(URL, params=params, stream=True) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 546, in get return self.request('GET', url, **kwargs) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request resp = self.send(prep, **send_kwargs) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs) File "/home/lbh/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&amp;id=1oAORKd-TPnPwZvhcnEEJqc1ogT7KgFtx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0325ff1310&gt;: Failed to establish a new connection: [Errno 110] Connection timed out'))
  
你解决了吗
  
我没有找到相应的数据集，你找到了吗
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by csjliang** [comment]
不好意思最近ddl有点忙。这是谷歌网盘的下载限制导致的，我已在readme中给出网页下载链接，请直接在网页上下载数据集，谢谢！

Sorry for the late reply. This error is caused by the download restriction of google drive. I have provided the download link in readme. Please download directly via this link. Thanks!
