### ISSUE TITLE
About summer2winter dataset

### ISSUE THREAD

**Issue by hughwcq** [csjliang/LPTN#39]
Hi,thank you for your wonderful work! i want to train a summer2winter model,but there is no a HD dataset. so can you share your summer2winter dataset,please? thanks!

**Comment by Zhou-Q-J** [comment]
> Hi,thank you for your wonderful work! i want to train a summer2winter model,but there is no a HD dataset. so can you share your summer2winter dataset,please? thanks!
Do you hava sum2win dataset

**Comment by Zhou-Q-J** [comment]
> Hi,thank you for your wonderful work! i want to train a summer2winter model,but there is no a HD dataset. so can you share your summer2winter dataset,please? thanks!

do you hava sum2win dataset?

**Comment by hughwcq** [comment]
sorry,i don't have this HD dataset.



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 14, 2022 12:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [csjliang/LPTN] About summer2winter dataset (Issue #39)




  
Hi,thank you for your wonderful work! i want to train a summer2winter model,but there is no a HD dataset. so can you share your summer2winter dataset,please? thanks!
  
do you hava sum2win dataset?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zhou-Q-J** [comment]
hello，I don't think the change is particularly noticeable, do you know why? Is there another loss function to add? Looking forward to your reply, thank you!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csjliang/LPTN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 凌晨1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csjliang/LPTN] About summer2winter dataset (Issue #39)





 sorry,i don't have this HD dataset. 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Mon, Mar 14, 2022 12:16 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [csjliang/LPTN] About summer2winter dataset (Issue #39) 
 
 
 
 
    
 Hi,thank you for your wonderful work! i want to train a summer2winter model,but there is no a HD dataset. so can you share your summer2winter dataset,please? thanks! 
    
 do you hava sum2win dataset? 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hughwcq** [comment]
because the translation is most in the low frequency domain.the low frequency domains just control the light and color.so the results are more like the color translation and don't change the high frequency domains so much,such as the edge, the texture and so on.



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 15, 2022 12:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [csjliang/LPTN] About summer2winter dataset (Issue #39)




 hello，I don't think the change is particularly noticeable, do you know why? Is there another loss function to add? Looking forward to your reply, thank you! 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "csjliang/LPTN"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年3月15日(星期二) 凌晨1:51 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [csjliang/LPTN] About summer2winter dataset (Issue #39) 
 
 
 
 
 
  sorry,i don't have this HD dataset.  
   
   
   
  ---Original---  
  From: ***@***.***&amp;amp;gt;  
  Date: Mon, Mar 14, 2022 12:16 PM  
  To: ***@***.***&amp;amp;gt;;  
  Cc: ***@***.******@***.***&amp;amp;gt;;  
  Subject: Re: [csjliang/LPTN] About summer2winter dataset (Issue #39)  
   
   
   
   
      
  Hi,thank you for your wonderful work! i want to train a summer2winter model,but there is no a HD dataset. so can you share your summer2winter dataset,please? thanks!  
      
  do you hava sum2win dataset?  
     
  —  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.   
  You are receiving this because you authored the thread.Message ID: ***@***.***&amp;amp;gt;  
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by csjliang** [comment]
> Hi,thank you for your wonderful work! i want to train a summer2winter model,but there is no a HD dataset. so can you share your summer2winter dataset,please? thanks!

Hi, sorry for the late reply.
As considering the copyright issues, please send me an email to get the link of the dataset. Thanks!
